# Generated by Django 3.2.5 on 2021-07-19 08:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0002_auto_20210719_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
    ]
