# Generated by Django 3.2.5 on 2021-07-20 07:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0003_alter_questionnaire_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None)),
                ('description', models.TextField()),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('type', models.CharField(default='Full Time', max_length=15)),
                ('experience_min', models.IntegerField()),
                ('experience_max', models.IntegerField()),
                ('category', models.CharField(default='Development', max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('meta_createdAt', models.DateTimeField(auto_now_add=True)),
                ('meta_updatedAt', models.DateTimeField(auto_now_add=True)),
                ('meta_owner', models.CharField(max_length=20)),
            ],
        ),
    ]
