# Generated by Django 3.2.5 on 2021-07-26 04:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0004_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='meta_createdAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='meta_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='meta_updatedAt',
            new_name='updatedAt',
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(default=70000),
        ),
        migrations.AlterField(
            model_name='job',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=None),
        ),
    ]
