# Generated by Django 3.2.5 on 2021-07-26 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0005_auto_20210726_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 10, 58, 54, 512230), editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 10, 58, 54, 512230)),
        ),
    ]
