# Generated by Django 3.2.5 on 2021-07-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0006_auto_20210726_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
