# Generated by Django 3.2.5 on 2021-07-27 09:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0008_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(default='Development', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(default='Full Time', max_length=50),
        ),
    ]
