# Generated by Django 3.2.5 on 2021-07-28 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0009_auto_20210727_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
