# Generated by Django 3.2.5 on 2021-07-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0010_alter_job_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnairePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_pages', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_id', to='dataApis.questionnaire')),
            ],
        ),
    ]
