# Generated by Django 3.2.5 on 2021-07-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0012_questionnairepages_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairepages',
            name='questionnaire_pages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_id', to='dataApis.questionnaire'),
        ),
    ]
