# Generated by Django 3.2.5 on 2021-07-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0013_alter_questionnairepages_questionnaire_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='form_id',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='QuestionnairePages',
        ),
    ]
