# Generated by Django 3.2.5 on 2021-07-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0014_auto_20210728_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_id', to='dataApis.form'),
        ),
    ]
