# Generated by Django 3.2.5 on 2021-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0015_auto_20210728_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(default='new form'),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(default=1, max_length=64),
        ),
    ]
