# Generated by Django 3.2.5 on 2021-07-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0016_auto_20210728_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='form_id',
            new_name='form',
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
