# Generated by Django 3.2.5 on 2021-07-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0017_auto_20210728_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataApis.form'),
        ),
    ]
