# Generated by Django 3.2.5 on 2021-08-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0020_auto_20210804_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='note',
            field=models.TextField(default='nakaroyaar'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(default='halo'),
        ),
    ]
