# Generated by Django 3.2.5 on 2021-08-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApis', '0021_auto_20210804_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
